CREATE TABLE IF NOT EXISTS blockchains (
    id          SERIAL          PRIMARY KEY,
    name        VARCHAR (100)   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
